/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/grepory/gentest/pkg/apis/basic/v1"
	scheme "github.com/grepory/gentest/pkg/client/clientset/internalclientset/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// BasicTypesGetter has a method to return a BasicTypeInterface.
// A group's client should implement this interface.
type BasicTypesGetter interface {
	BasicTypes(namespace string) BasicTypeInterface
}

// BasicTypeInterface has methods to work with BasicType resources.
type BasicTypeInterface interface {
	Create(*v1.BasicType) (*v1.BasicType, error)
	Update(*v1.BasicType) (*v1.BasicType, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.BasicType, error)
	List(opts metav1.ListOptions) (*v1.BasicTypeList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.BasicType, err error)
	BasicTypeExpansion
}

// basicTypes implements BasicTypeInterface
type basicTypes struct {
	client rest.Interface
	ns     string
}

// newBasicTypes returns a BasicTypes
func newBasicTypes(c *BasicV1Client, namespace string) *basicTypes {
	return &basicTypes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the basicType, and returns the corresponding basicType object, and an error if there is any.
func (c *basicTypes) Get(name string, options metav1.GetOptions) (result *v1.BasicType, err error) {
	result = &v1.BasicType{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("basictypes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of BasicTypes that match those selectors.
func (c *basicTypes) List(opts metav1.ListOptions) (result *v1.BasicTypeList, err error) {
	result = &v1.BasicTypeList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("basictypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested basicTypes.
func (c *basicTypes) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("basictypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a basicType and creates it.  Returns the server's representation of the basicType, and an error, if there is any.
func (c *basicTypes) Create(basicType *v1.BasicType) (result *v1.BasicType, err error) {
	result = &v1.BasicType{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("basictypes").
		Body(basicType).
		Do().
		Into(result)
	return
}

// Update takes the representation of a basicType and updates it. Returns the server's representation of the basicType, and an error, if there is any.
func (c *basicTypes) Update(basicType *v1.BasicType) (result *v1.BasicType, err error) {
	result = &v1.BasicType{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("basictypes").
		Name(basicType.Name).
		Body(basicType).
		Do().
		Into(result)
	return
}

// Delete takes name of the basicType and deletes it. Returns an error if one occurs.
func (c *basicTypes) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("basictypes").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *basicTypes) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("basictypes").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched basicType.
func (c *basicTypes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.BasicType, err error) {
	result = &v1.BasicType{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("basictypes").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
