/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	basicv1 "github.com/grepory/gentest/pkg/apis/basic/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBasicTypes implements BasicTypeInterface
type FakeBasicTypes struct {
	Fake *FakeBasicV1
	ns   string
}

var basictypesResource = schema.GroupVersionResource{Group: "basic", Version: "v1", Resource: "basictypes"}

var basictypesKind = schema.GroupVersionKind{Group: "basic", Version: "v1", Kind: "BasicType"}

// Get takes name of the basicType, and returns the corresponding basicType object, and an error if there is any.
func (c *FakeBasicTypes) Get(name string, options v1.GetOptions) (result *basicv1.BasicType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(basictypesResource, c.ns, name), &basicv1.BasicType{})

	if obj == nil {
		return nil, err
	}
	return obj.(*basicv1.BasicType), err
}

// List takes label and field selectors, and returns the list of BasicTypes that match those selectors.
func (c *FakeBasicTypes) List(opts v1.ListOptions) (result *basicv1.BasicTypeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(basictypesResource, basictypesKind, c.ns, opts), &basicv1.BasicTypeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &basicv1.BasicTypeList{ListMeta: obj.(*basicv1.BasicTypeList).ListMeta}
	for _, item := range obj.(*basicv1.BasicTypeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested basicTypes.
func (c *FakeBasicTypes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(basictypesResource, c.ns, opts))

}

// Create takes the representation of a basicType and creates it.  Returns the server's representation of the basicType, and an error, if there is any.
func (c *FakeBasicTypes) Create(basicType *basicv1.BasicType) (result *basicv1.BasicType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(basictypesResource, c.ns, basicType), &basicv1.BasicType{})

	if obj == nil {
		return nil, err
	}
	return obj.(*basicv1.BasicType), err
}

// Update takes the representation of a basicType and updates it. Returns the server's representation of the basicType, and an error, if there is any.
func (c *FakeBasicTypes) Update(basicType *basicv1.BasicType) (result *basicv1.BasicType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(basictypesResource, c.ns, basicType), &basicv1.BasicType{})

	if obj == nil {
		return nil, err
	}
	return obj.(*basicv1.BasicType), err
}

// Delete takes name of the basicType and deletes it. Returns an error if one occurs.
func (c *FakeBasicTypes) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(basictypesResource, c.ns, name), &basicv1.BasicType{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBasicTypes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(basictypesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &basicv1.BasicTypeList{})
	return err
}

// Patch applies the patch and returns the patched basicType.
func (c *FakeBasicTypes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *basicv1.BasicType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(basictypesResource, c.ns, name, data, subresources...), &basicv1.BasicType{})

	if obj == nil {
		return nil, err
	}
	return obj.(*basicv1.BasicType), err
}
